# OpenShift overlay for hosted deployment
# TODO: Add OpenShift-specific resources:
# - Routes for external access (instead of NodePort)
# - ImagePullSecrets for private registry
# - OpenShift-compatible security context constraints
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - storage/persistent-volume-claims.yaml

# OpenShift-specific resources will be added here:
# - routes.yaml (OpenShift Routes)
# - image-pull-secret.yaml

# Patches for OpenShift compatibility will be added here
